import { describe, expect, it } from "vitest";
import type { SalesSummaryResponse } from "@kassa/schemas/salesSummary";
import { buildSalesSummaryCsv, renderSalesSummaryPrintHtml } from "../src/lib/salesSummary";

/*
 * Unit tests for the back-office "Ringkasan periode" export helpers (KASA-327).
 *
 * Two surfaces are pinned here:
 *   1. CSV — pre-pinned schema so the merchant's accountant doesn't get a
 *      column reshuffle every release. Numbers stay as raw integers (no
 *      thousands separator) so Excel parses cells as numbers, and the
 *      response carries a UTF-8 BOM so Windows-Excel opens id-ID strings
 *      without mojibake.
 *   2. Print HTML — sanity-check that the report renders with the period
 *      header, totals, breakdown, and "Generated by Kassa" footer the
 *      acceptance criteria asks for. We don't go pixel-perfect; we just
 *      confirm the right strings + tabular numbers land.
 */

const HEADER_LABELS = {
  key: "Tanggal",
  label: "Label",
  gross: "Bruto",
  discount: "Diskon",
  tax: "PPN",
  net: "Net",
  saleCount: "JumlahTransaksi",
  refundCount: "JumlahRefund",
  refundIdr: "NilaiRefund",
  quantity: "Jumlah",
};

const TENDER_LABELS = {
  cash: "Tunai",
  qris_dynamic: "QRIS dinamis",
  qris_static: "QRIS statis",
};

const PRINT_LABELS = {
  gross: "Pendapatan kotor",
  discount: "Diskon",
  tax: "PPN",
  net: "Pendapatan bersih",
  saleCount: "Jumlah transaksi",
  refundCount: "Jumlah refund",
  refundIdr: "Nilai refund",
  tenderMix: "Komposisi pembayaran",
  topItems: "Produk teratas",
  breakdown: "Rincian per bucket",
  rangeFooter: "Disusun otomatis oleh Kassa untuk periode 2026-04-01 – 2026-04-30.",
};

function dayGroupedSummary(): SalesSummaryResponse {
  return {
    outletId: null,
    from: "2026-04-01",
    to: "2026-04-30",
    groupBy: "day",
    grossIdr: 100_000,
    discountIdr: 5_000,
    taxIdr: 9_900,
    netIdr: 90_100,
    saleCount: 4,
    refundCount: 1,
    refundIdr: 25_000,
    tenderMix: [
      { method: "cash", amountIdr: 60_000, count: 2 },
      { method: "qris_dynamic", amountIdr: 40_000, count: 2 },
    ],
    topItemsByRevenue: [
      {
        itemId: "01890abc-1234-7def-8000-0000000c0001",
        name: "Kopi Susu",
        revenueIdr: 50_000,
        quantity: 3,
      },
    ],
    topItemsByQuantity: [
      {
        itemId: "01890abc-1234-7def-8000-0000000c0001",
        name: "Kopi Susu",
        revenueIdr: 50_000,
        quantity: 3,
      },
    ],
    groups: [
      {
        key: "2026-04-01",
        label: "2026-04-01",
        grossIdr: 70_000,
        discountIdr: 3_000,
        taxIdr: 6_930,
        netIdr: 63_070,
        saleCount: 3,
        refundCount: 0,
        refundIdr: 0,
        quantity: 0,
      },
      {
        key: "2026-04-02",
        label: "2026-04-02",
        grossIdr: 30_000,
        discountIdr: 2_000,
        taxIdr: 2_970,
        netIdr: 27_030,
        saleCount: 1,
        refundCount: 1,
        refundIdr: 25_000,
        quantity: 0,
      },
    ],
  };
}

describe("buildSalesSummaryCsv (groupBy=day)", () => {
  it("emits a UTF-8 BOM followed by the period comment + header row", () => {
    const csv = buildSalesSummaryCsv({
      summary: dayGroupedSummary(),
      groupByLabel: "Per hari",
      headerLabels: HEADER_LABELS,
    });
    expect(csv.charCodeAt(0)).toBe(0xfeff);
    expect(csv).toContain("# Periode: 2026-04-01 → 2026-04-30 · Per hari · outlet: semua");
    expect(csv).toContain(
      "Tanggal,Label,Bruto,Diskon,PPN,Net,JumlahTransaksi,JumlahRefund,NilaiRefund",
    );
  });

  it("writes one row per day with raw-integer rupiah cells (no thousands separator)", () => {
    const csv = buildSalesSummaryCsv({
      summary: dayGroupedSummary(),
      groupByLabel: "Per hari",
      headerLabels: HEADER_LABELS,
    });
    expect(csv).toContain("2026-04-01,2026-04-01,70000,3000,6930,63070,3,0,0");
    expect(csv).toContain("2026-04-02,2026-04-02,30000,2000,2970,27030,1,1,25000");
    // Spot-check: no "Rp" prefix or "." grouping — Excel must see numbers.
    expect(csv).not.toMatch(/Rp/);
    expect(csv).not.toMatch(/70\.000/);
  });

  it("uses item-specific columns when groupBy=item", () => {
    const summary = dayGroupedSummary();
    summary.groupBy = "item";
    summary.groups = [
      {
        key: "01890abc-1234-7def-8000-0000000c0001",
        label: "Kopi Susu",
        grossIdr: 50_000,
        discountIdr: 0,
        taxIdr: 0,
        netIdr: 50_000,
        saleCount: 0,
        refundCount: 0,
        refundIdr: 0,
        quantity: 3,
      },
    ];
    const csv = buildSalesSummaryCsv({
      summary,
      groupByLabel: "Per produk",
      headerLabels: HEADER_LABELS,
    });
    expect(csv).toContain("Tanggal,Label,Bruto,Jumlah");
    expect(csv).toContain("01890abc-1234-7def-8000-0000000c0001,Kopi Susu,50000,3");
    // No discount / tax / refund columns in item mode.
    expect(csv).not.toContain("JumlahTransaksi");
  });

  it("quotes cells containing commas, quotes, or newlines", () => {
    const summary = dayGroupedSummary();
    summary.groups = [
      {
        ...summary.groups[0]!,
        label: 'Es Kopi, "Susu" Vanilla',
      },
    ];
    const csv = buildSalesSummaryCsv({
      summary,
      groupByLabel: "Per hari",
      headerLabels: HEADER_LABELS,
    });
    expect(csv).toContain('"Es Kopi, ""Susu"" Vanilla"');
  });
});

describe("renderSalesSummaryPrintHtml", () => {
  it("renders the heading, period header, totals, breakdown, and footer", () => {
    const html = renderSalesSummaryPrintHtml({
      summary: dayGroupedSummary(),
      headingLabel: "Ringkasan periode",
      groupByLabel: "Per hari",
      groupByColumnLabel: "Tanggal",
      tenderLabelsByMethod: TENDER_LABELS,
      labels: PRINT_LABELS,
    });

    expect(html).toContain("<!doctype html>");
    expect(html).toContain("<title>Ringkasan periode 2026-04-01 – 2026-04-30</title>");
    expect(html).toContain("<h1>Ringkasan periode</h1>");
    expect(html).toContain("2026-04-01 → 2026-04-30 · Per hari");
    // Headline tiles render the formatted IDR amount.
    expect(html).toContain("Pendapatan kotor");
    expect(html).toContain("Rp 100.000");
    // Tender mix uses the localised labels.
    expect(html).toContain("Tunai");
    expect(html).toContain("QRIS dinamis");
    // Breakdown table includes both day rows.
    expect(html).toContain("2026-04-01");
    expect(html).toContain("2026-04-02");
    // Top items section renders the leaderboard.
    expect(html).toContain("1. Kopi Susu");
    // Footer carries the date range.
    expect(html).toContain("Disusun otomatis oleh Kassa untuk periode 2026-04-01 – 2026-04-30.");
  });

  it("escapes potentially-hostile group labels", () => {
    const summary = dayGroupedSummary();
    summary.groups[0]!.label = "<script>alert(1)</script>";
    const html = renderSalesSummaryPrintHtml({
      summary,
      headingLabel: "Ringkasan periode",
      groupByLabel: "Per hari",
      groupByColumnLabel: "Tanggal",
      tenderLabelsByMethod: TENDER_LABELS,
      labels: PRINT_LABELS,
    });
    expect(html).not.toContain("<script>alert(1)</script>");
    expect(html).toContain("&lt;script&gt;alert(1)&lt;/script&gt;");
  });
});
